### ISSUE TITLE
Install does not run or publish migrations

### ISSUE THREAD

**Issue by adampatterson** [bezhanSalleh/filament-exceptions#11]
I had to publish the migrations manually to complete the installation.

![image](https://user-images.githubusercontent.com/31537/198740055-8fda014a-7990-4d9d-b202-ec890b03cd4e.png)

**Comment by Szucs996** [comment]
Had the same issue.

**Comment by abdulmejidshemsu** [comment]
same issue

**Comment by sandervanh** [comment]
Same

**Comment by Beaudinn** [comment]
same
