### ISSUE TITLE
Not enough context

### ISSUE THREAD

**Issue by damms005** [bezhanSalleh/filament-exceptions#18]
This really should be a feature request, but the feature request issue creation button currently  displays error 404 (screenshot attached)

The exception should display the authenticated user (like Laravel Telescope does, screenshot also attached).

![image](https://user-images.githubusercontent.com/9839355/204144015-b55ead29-b50a-4a13-876d-6abf603e6758.png)
![image](https://user-images.githubusercontent.com/9839355/204143479-8224d764-d590-4eae-9ada-3e8b3f79f7b7.png)

**Comment by bezhanSalleh** [comment]
PR it.
