### ISSUE TITLE
restrict `Exception` access to few roles only using `filament-shield`

### ISSUE THREAD

**Issue by apaleja** [bezhanSalleh/filament-exceptions#21]
I am trying to restrict access to `Exception` page to certain roles only using `filament-shield` i.e. `admin` but all the users are able to see and access it. is there any specific steps I need to follow apply generated policy to restrict access ?

**Comment by NoahNxT** [comment]
Same issue here, any solution yet?

**Comment by bezhanSalleh** [comment]
filament exceptions doesn't come with a default policy so first [generate](https://github.com/bezhanSalleh/filament-shield#shieldgenerate) the policy using shield and then enforce it. read on here [Shield third-party-plugins](https://github.com/bezhanSalleh/filament-shield#third-party-plugins)
