### ISSUE TITLE
Filament v3: Missing info: Register plugin

### ISSUE THREAD

**Issue by vanhooff** [bezhanSalleh/filament-exceptions#36]
Hi,

This plugin is missing Filament V3 installation info: 

**4. Register the plugin for the Filament Panel**

```
public function panel(Panel $panel): Panel
{
    return $panel
        ->plugins([
            \BezhanSalleh\FilamentExceptions\FilamentExceptionsPlugin::make()
        ]);
}
```

**Comment by bezhanSalleh** [comment]
Thanks, could you instead do PR and review the readme and make sure it's descriptive enough for v3.
