### ISSUE TITLE
Allow for custom model

### ISSUE THREAD

**Issue by Fludem** [bezhanSalleh/filament-exceptions#44]
Hey,

Can you allow for custom model?

I'm using multiple database tenancy so need to modify the model to use the central connection :)

Thanks

**Comment by bezhanSalleh** [comment]
> Hey,
> 
> 
> 
> Can you allow for custom model?
> 
> 
> 
> I'm using multiple database tenancy so need to modify the model to use the central connection :)
> 
> 
> 
> Thanks
> 
> 

Wont be able to do it any time soon. But if you could make a PR i will make sure to do a release.

**Comment by Fludem** [comment]
Yah I'll fork right now and I'll submit it shortly.

Well, might be a few days a lil busy!
