### ISSUE TITLE
SPA mode: No line numbers or syntax highlighting

### ISSUE THREAD

**Issue by binaryfire** [bezhanSalleh/filament-exceptions#51]
Hi! I've noticed a problem with SPA mode. Line numbers and syntax highlighing aren't visible when viewing an exception. Refreshing the browser while on the exceptions page fixes the issue. I'm guessing the problem is that the assets aren't being loaded when using `wire:navigate` to navigate to the exceptions page.

<img width="1039" alt="image" src="https://github.com/bezhanSalleh/filament-exceptions/assets/5361908/d8030ae6-788a-4c4c-8902-351cdb0afbec">

**Comment by bezhanSalleh** [comment]
haven't used spa mode so have no idea apologies.
