### ISSUE TITLE
Unsupport subquery for delete histories

### ISSUE THREAD

**Issue by warsemann** [bezhanSalleh/filament-exceptions#62]
Hi, my version of mysql is 8.4 and i ve this message on job that delete the history :

`SQLSTATE[42000]: Syntax error or access violation: 1235 This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery' (Connection: mysql, SQL: delete from `schedule_histories` where `schedule_histories`.`schedule_id` = 1 and `schedule_histories`.`schedule_id` is not null and `id` not in (select `id` from `schedule_histories` where `schedule_histories`.`schedule_id` = 1 and `schedule_histories`.`schedule_id` is not null order by `created_at` desc limit 30))`

**Comment by bezhanSalleh** [comment]
i don't think this is related to the plugin but if you can submit repro repo i will take a look at it.
